### ISSUE TITLE
Actionbar Paging not working

### ISSUE THREAD

**Issue by mbesto** [coolmodi/SpellCalc#15]
If you page through an actionbar, the 2nd actionbar doesn't have the amounts on the overlay. 

Steps to reproduce:

- Have spells on the first page of the actionbar
- Switch to the 2nd page
- I expected the 2nd page spells to have the spell amounts on the overlay. Instead I see the first page spells amounts still persisting

**Comment by coolmodi** [comment]
Sorry for the late reply, Scarablord event and RL take all my time atm :)

There is no support for paging at all because I honestly didn't think anybody uses it. There is only basic support for stances/forms for the main actionbar implemented. 

I'll look back into this when I have time again, but don't expect an update this month, there are also other things that need to be done with this addon. If it turns out to be super easy to do it may come sooner though.

**Comment by coolmodi** [comment]
Version 0.8.2 now has full paging support.
