### ISSUE TITLE
Priest: Mana Burn isn't considered

### ISSUE THREAD

**Issue by yeaido** [coolmodi/SpellCalc#30]
All you get is the default tooltip:
![image](https://user-images.githubusercontent.com/23041803/125968480-1b1b9fa3-50e4-45b2-aa23-d1cf2825ab27.png)

**Comment by coolmodi** [comment]
I haven't added this spell because it simply wouldn't show anything interesting imho. The mana burnt doesn't scale with anything I know of. The damage caused scales with damage taken modifiers on the target which aren't (yet) implemented. I guess Shadowform should also increase the damage part, but not even sure about that.

**Comment by yeaido** [comment]
My bad I always thought mana burn scaled with something but I've not found anything to support that belief.
