### ISSUE TITLE
Paladin HoW

### ISSUE THREAD

**Issue by Jinnai** [coolmodi/SpellCalc#34]
HoW isn't showing any crit in the tooltip. Also the hit chance is off. It shows 26% hit (23% + 3%) against +2 level targets.

**Comment by coolmodi** [comment]
Wanted to fix that forever, but I still don't know how HoW is supposed to work. It is a ranged attack (like a hunter shot) that does holy damage, unlike e.g. Judgement of Command and Blood, which are melee holy attacks that use your melee weapon skill for hit and crit calculation.

What weapon skill does HoW use? Does it actually use ranged hit and crit? I simply don't know.

Paladin doesn't have a ranged weapon, which is why it currently uses whatever value the game spits out as your ranged skill, even though that obviously can't be right and causes crit chance to become 0 and hit chance to be super low when targeting NPCs.

**Comment by coolmodi** [comment]
Works in wrath update (0.17)
